### ISSUE TITLE
Youtube link

### ISSUE THREAD

**Issue by eringrand** [barryclark/jekyll-now#102]
I'd like to include a link to my youtube in my footer. I've changed the default page to include the link, and the _config file to keep track of the URL, but I don't know how to get the icon to work. I have the image I want (attached) but need to figure out how to get it into the right format for the _svg-icons.scss file. Any sugggestions?

![youtube-social-circle_red_48px](https://cloud.githubusercontent.com/assets/6360871/6145320/8f5b5b0a-b1ae-11e4-9178-d76b3fe2ea58.png)

**Comment by barryclark** [comment]
Fixed and merged in, see #121 :octocat:
