### ISSUE TITLE
how Jekill load pages

### ISSUE THREAD

**Issue by rinaldi6109** [barryclark/jekyll-now#1068]
I'm a totally newbye.
I wish to know how Jekill load pages. 
That is, how is it possible that it loads content from My-title.md file inside the _posts subfolder **displaying the url** myname.github.io/_posts/201x-xx-xx-My title in the address bar (since such url does not exists)? I think it is not a specific question related to Jekill but I sincerely wish to know...
Thanks for your patience.

**Comment by wolfy1339** [comment]
Jekyll compiles the markdown files into HTML, then a webserver serves that built HTML

**Comment by JuanjoSalvador** [comment]
Markdown is magical, and we can compile md files into HTML files, PDF, or whatever we want.

Jekyll has a set of rules (you can modify some of them) about how to build your site. There is a bunch of special folders that contains fragments of your site (head, body, content, etc) and Jekyll knows how to use all of them. The next stage is join the pieces. Your MD content can be compiled as HTML content, and join to the party.

Then all the builded site appears on `_site`. Magical.

The core set of rules is on `_config.yml` file, and you can modify the fragments as you like. I strongly recommend you to check the Jekyll site and learn how to build your own theme, that's very good way to learn how Jekyll works.
