### ISSUE TITLE
Preview cuts off in middle of code block and renders rest of front page in code font

### ISSUE THREAD

**Issue by bewuethr** [barryclark/jekyll-now#109]
The front page shows the first six or so lines of each post and then the "READ MORE" link. However, if the last line displayed before that is in the middle of a code block, the rest of the front page gets rendered in the corresponding font:

![capture](https://cloud.githubusercontent.com/assets/8521043/6184561/621d49f8-b331-11e4-9510-c4347e76d370.jpg)

**Comment by barryclark** [comment]
Fixed with https://github.com/barryclark/jekyll-now/commit/ac1cf36fe024843fd7173ec4d5feb62c53285997

See discussion at https://github.com/barryclark/jekyll-now/issues/117 for more info.
