### ISSUE TITLE
Add text at the footer?

### ISSUE THREAD

**Issue by averyburnettmiller** [barryclark/jekyll-now#110]
Hey! I'd like to add text (Copyright text, etc.) to the bottom of my jekyll-now site. Any way I can do this? What file should I edit?

**Comment by cjerrington** [comment]
the default.html layout in the _layouts folder is where you can change this. 

add <p>&copy; {{ site.name }} 2015 | All Rights Reserved. </p> to the  <footer class="footer">  or what ever content you'd like. I did that to my site, claytonerrington.com

**Comment by cjerrington** [comment]
@averyburnettmiller a better copyright would be 

``` ruby
<p>&copy; {{ site.name }} {{ site.time | date: '%Y' }} | All Rights Reserved. </p>
```

the ``` ruby  {{ site.time | date: '%Y' }} ``` gets the time and outputs the whole year, 2015, and wont need to change this each year.

**Comment by barryclark** [comment]
Ooo, that's an especially nice fix @cjerrington. Closing this :smiley:

**Comment by averyburnettmiller** [comment]
Thanks!

**Comment by alihusnainarshad** [comment]
@cjerrington  **Thank You**   

`<p>&copy; {{ site.name }} {{ site.time | date: '%Y' }} | All Rights Reserved. </p>`

**Worked Perfectly** 💕
