### ISSUE TITLE
page not found even if i edited the _config.yml

### ISSUE THREAD

**Issue by estelll** [barryclark/jekyll-now#1130]
I forked the repository and renamed it to 'username.github.io'
And then I opened'username.github.io' but it is the 404 page.
I edited the _config.yml to set the name and description. Then I opened the site again. Still, it is not found.
I waited for at least 10 minutes. Still not found...
Then I edited url in the _config.yml to 'http://username.github.io'. And then I opened the site. Failed.
Wait for 10 minutes. Still failed.

What's wrong.

**Comment by pSnehanshu** [comment]
Hey, it seems like your website is up and running at [estelll.github.io](https://estelll.github.io/). Maybe you should close this issue.
