### ISSUE TITLE
truncatewords is unsafe

### ISSUE THREAD

**Issue by annam002** [barryclark/jekyll-now#117]
Hi,
thanks for this easy starting point with jekyll!

I just want to make you aware that this line in index.html is unsafe:
 `{{ post.content | truncatewords:40}}`
Depending of what you have in your post, you might be in the middle of markup. I am not entirely sure why, but in our page it resulted in strange `<em>`  tags appearing. I switched it now to use the 
`{{ post.excerpt }}` 
tag with a custom excerpt separator and that works better.

Best,
Anna

**Comment by bewuethr** [comment]
Exactly the probem I had in #109.

**Comment by barryclark** [comment]
Thanks for the comments, @bewuethr and @annam002.

I can see two good options for fixing this:

1. {{ post.excerpt }} as Anna mentioned.
2. {{ post.content }} without truncating, displaying the whole posts on your homepage.

Any thoughts on whether you guys would prefer the whole post to appear on the homepage, or just the first paragraph of each post as a teaser?

**Comment by bewuethr** [comment]
I think it depends a bit on the type of posts, but I'd personally prefer teasers and a "read more" link.

**Comment by barryclark** [comment]
Thanks @bewuethr. I'm thinking leaning towards making {{ post.excerpt }} the default behavior, and having an option in _config.yml to display full posts on the homepage.

**Comment by annam002** [comment]
I agree, seeing only the excerpts first makes it look nicer. However, maybe you could then also prepare a custom excerpt separator in the config file. Something like this:
`# excerpt_separator: <!---more--->  # Use this to separate post excerpt from full content of post`

**Comment by etelej** [comment]
Just wanted to share what I do:

```jekyll
{{ post.content |strip_html |replace:'  ',' '|replace:'  ',' '|replace:'  ',' '|replace:'  ',' '|replace:'  ',' '|replace:'  ',' '|replace:'  ',' '|replace:'  ',' '|replace:'  ',' '|replace:'  ',' '|replace:'  ',' '|replace:'  ',' '| truncate:200  }}
```

Most important parts: 
- `strip_html` - to remove undesired html tags (e.g links, etc) 
- `replace:'  ',' '` - to get rid of whitespacing

I then use 'read more' icon. It doesn't look nice, but it gives text content for an excerpt. Though, it's too cluttery for j-now

**Comment by barryclark** [comment]
```{{ post.excerpt }}``` it is! I think that simple fix should be enough for most people. Folk can always look into ```excerpt_separator``` if they want more control. Thanks guys :beers:

**Comment by zhiwei-ID** [comment]
good
