### ISSUE TITLE
Use Jekyll-now with Project site

### ISSUE THREAD

**Issue by yeonggyulim** [barryclark/jekyll-now#1186]
Can I use Jekyll-now this way?
{username}.github.io/{repositoryname}?

**Comment by PTrottier** [comment]
@yeonggyulim I have been successful in achieving this by rename my repository after forking.

**Comment by yeonggyulim** [comment]
> @yeonggyulim I have been successful in achieving this by rename my repository after forking.

Thank you. it worked
