### ISSUE TITLE
Atom feed

### ISSUE THREAD

**Issue by irudnyts** [barryclark/jekyll-now#1204]
I use Jekyll Now template and host it on Github Pages to run my blog. I need to create an Atom (RSS) feed.

I found that there is a plugin for that, which is supposed to work for Github Pages 2. I have ensured that `_config.yml` file contains `jekyll-feed` in  `plugins` section. Also, I filled in `footer-links:` section to make RSS work, as well as `url:` (my web-page is stored in my User repository).

For some reason, it does not work (meaning no feed.xml file was generated).

What am I missing?

The link to repo is http://github.com/irudnyts/irudnyts.github.io

**Comment by ldjb** [comment]
Hi, it does work! Your blog's Atom feed is accessible at:
https://irudnyts.github.io/feed.xml

You can also access this feed by clicking the relevant icon in the footer of your blog, or by using your web browser's subscribe feature.

Note that you may need to perfom a "hard refresh" if you are getting a 404 error message when trying to access the feed. Please refer to your web browser's documentation for information on how to do this.

**Comment by irudnyts** [comment]
Thanks a lot for your answer. Indeed, it works. I believe it was a delay in generating the file, and I was not patient enough.
