### ISSUE TITLE
Add google analytics anonymizeIp option

### ISSUE THREAD

**Issue by Shupal** [barryclark/jekyll-now#123]
Hi,

thanks for this great repository! i love it <3
Maybe it is a good suggestion to add a google analytics anonymizeip variable in the _config file.

```javascript
ga('set', 'anonymizeIp', true);
```

And then use it like that 

```javascript
ga('create', '{{ site.google_analytics }}', 'auto');
{% if site.google_analytics_anonymizeip %}
ga('set', 'anonymizeIp', true);
{% endif %}
ga('send', 'pageview');
```
or is there a better way to handle that?

Best,
Stefan

**Comment by barryclark** [comment]
Thanks, Stefan!

And thanks for your suggestion! I'm not to sure that this is something that many users would need? I asked a few friends and no-one had heard of [anonymizeIP](https://support.google.com/analytics/answer/2763052?hl=en), I hadn't either. 

I think that this would be a feature that people would add to their own fork if needed, going to close this one out.

Cheers,
Barry
