### ISSUE TITLE
wrote new post rmd file and ran rmd2md, but not appeared on the web

### ISSUE THREAD

**Issue by jianlianggao** [barryclark/jekyll-now#1252]
Hi Barry,

I followed your instructions and composed a .rmd file in the "_rmd" dir. Then I ran rmd2md.r to compile the file. The compiled file was generated in the _posts dir. But it didn't show on the web page after I pushed to my github. I also tried to modify the hello world .md file, but that didn't help either. Any advise please!

Many thanks,
BW,
Jianliang

**Comment by ldjb** [comment]
Hi,

I think you must have figured out the problem since the post is now displaying on the website:
https://jianlianggao.github.io/KubeNow-on-Azure/

But if you are still having issues, please say! :-)

**Comment by jianlianggao** [comment]
Hi Barry,

Many thanks, yes, I did. The issue was caused by the previously existing index.md file.

Best wishes,
Jianliang
