### ISSUE TITLE
The fork is not working...

### ISSUE THREAD

**Issue by Martinaws** [barryclark/jekyll-now#128]
Hello! I have followed the instruction and done the fork. However, it does not create a fork but redirects me to another fork that I did (from a project that was in turn forked by jekyll-now). Do you know why I am having this issue?
Thanks,
Martina

**Comment by barryclark** [comment]
This? https://github.com/Martinaws/BioHackAcademyPTBR.github.io

You need to rename the repository to be ```martinaws.github.io```

**Comment by Martinaws** [comment]
Hello! it redirects me to https://github.com/Martinaws/BioHackAcademyPTBR.github.io while instead I would like to create an additional one...

**Comment by barryclark** [comment]
I'm a bit confused about what you're aiming to do @Martinaws, so struggling to help. :disappointed: 

Maybe delete your fork and try again from the beginning?

**Comment by Martinaws** [comment]
Will try then!

Thanks,

Martina

*Martina Francesca Ferracane*
+32 48 787 0551
+39 329 363 8728

2015-03-07 21:09 GMT-03:00 Barry Clark <notifications@github.com>:

**Comment by barryclark** [comment]
How did it go @Martinaws?

**Comment by barryclark** [comment]
Gonna close out, but please re-open if you run into any more problems or have questions :)

**Comment by Martinaws** [comment]
Thanks for your email Barry! I actually gave up to trying to use GitHub. I know too little about coding and it was too complicated for me. Wish you a nice day, Marti 

Sent by iPhone
