### ISSUE TITLE
Add G+ Icons

### ISSUE THREAD

**Issue by plinioseniore** [barryclark/jekyll-now#137]
Hi, having G+ included in the option for social network would be great.

I don't know from where you get the icons, because in case you can provide a link and I can add by myseld

**Comment by eringrand** [comment]
Hey,  I worked a bit on getting the youtube icon to work, so I can quickly redo that to get you the code for the G+ icon, but if you're just looking for a place to find good SVG icons, Barry links to [this](https://github.com/neilorangepeel/Free-Social-Icons) repo.  In example [this link should go to the G+ one](https://github.com/neilorangepeel/Free-Social-Icons/blob/master/Flat/SVG/Google%20%2B.svg).

**Comment by eringrand** [comment]
If @barryclark wants is interested, I can write up a quick "How To" guide on the repo's wiki on where to find the icons and how to get them on your site.

**Comment by plinioseniore** [comment]
Hi Erin,

I saw that you pushed a code with the G+ icon, that's great!

Thanks,
Dario.

From Mobile.
