### ISSUE TITLE
Github page build failure

### ISSUE THREAD

**Issue by sanjsanj** [barryclark/jekyll-now#146]
Hello!
Firstly, thank you so much for your work on this repo, I'm immensely enjoying using it.  Recently I have begun to notice some page build failures, a few of them I've managed to circumvent but this one is really giving me problems.

So the below code is the offender:

{% highlight ruby linenos %}
require 'capybara/rspec'
require 'airport'

feature 'Grand Finale' do

  airport = Airport.new
  planes = []
  6.times { planes << Plane.new }
  p = Plane.new

  scenario '6 planes can be created' do
    expect(planes.length).to eq 6
  end

  scenario 'airport knows planes are in the air' do
    planes.each do |plane|
      expect(plane.location).to eq('air')
    end
  end

  scenario '6 planes can land at specified airport' do
    Airport.any_instance.stub(:weather_good).and_return(true)
    planes.each { |plane| plane.request_land airport }
    expect(airport.landed_planes.length).to eq 6
  end

  scenario 'airport knows planes are in the airport' do
    planes.each do |plane|
      expect(plane.location).to eq('airport')
    end
  end

  scenario 'plane is denied landing permission when airport is full' do
    Airport.any_instance.stub(:weather_good).and_return(true)
    expect { (p.request_land airport) }.to raise_error 'permission denied'
  end

  scenario '6 landed planes have status: landed' do
    airport.landed_planes.each do |plane|
      expect(plane.status).to eq 'landed'
    end
  end

  scenario 'after all 6 planes takeoff there are no more landed planes' do
    Airport.any_instance.stub(:weather_good).and_return(true)
    planes.each do |plane|
      airport.order_plane_takeoff plane
    end
    expect(airport.landed_planes.length).to eq 0
  end

  scenario 'after all 6 planes takeoff their status is \'flying\'' do
    planes.each do |plane|
      expect(plane.status).to eq 'flying'
    end
  end
end
{% endhighlight %}

------------

And this is the error email I get from Git:

The page build failed with the following error:

The tag `highlight` in `_posts/2015-03-22-Week` was not properly closed with `{% endhighlight %}`. For more information, see https://help.github.com/articles/page-build-failed-tag-not-properly-closed.

If you have any questions you can contact us by replying to this email.

**Comment by Koxzi95** [comment]
This is really strange. I've got it working on a page here with no issues or changes:
http://koxzi.me/Hello-World/
https://github.com/Koxzi95/koxzi95.github.io/blob/master/_posts/2014-10-04-Hello-World.md

**Comment by sanjsanj** [comment]
HI, thanks very much for testing this out.  Very strange I had issues with it, I'll see if I can try it again and see if still fails for me.

**Comment by barryclark** [comment]
How did it go @sanjsanj?

**Comment by sanjsanj** [comment]
@barryclark Sorry but I've yet to revisit this issue, I've conditioned myself to use safer syntax and avoid problematic snippets so I've not encountered a page build in a while.  If I have any more light to shed I'll update here.  
My Thanks to you and @Koxzi95

**Comment by barryclark** [comment]
:+1:

**Comment by wyh8590051** [comment]
Excerpts

Since v1.0.0, Jekyll has had automatically-generated post excerpts. Since v1.1.0, Jekyll also passes these excerpts through Liquid, which can cause strange errors where references don’t exist or a tag hasn’t been closed. If you run into these errors, try setting **excerpt_separator: ""** in your _config.yml, or set it to some nonsense string.

This works for me.
For more:  https://jekyllrb.com/docs/troubleshooting/
