### ISSUE TITLE
Page width

### ISSUE THREAD

**Issue by scra88le** [barryclark/jekyll-now#1461]
Hi, I'd like to widen the page so I can fit more text on the screen - is there any easy way to configure this?
Thanks

**Comment by vishaldodiya** [comment]
Increase Container width from here. https://github.com/barryclark/jekyll-now/blob/master/style.scss#L28
I think it will do the work.

Right now it's 👇 
```
.container {
  margin: 0 auto;
  max-width: 740px;
  padding: 0 10px;
  width: 100%;
}
```

**Comment by scra88le** [comment]
That worked! Thank you.
