### ISSUE TITLE
hoverZoomLink class appended to images

### ISSUE THREAD

**Issue by mkess-ivy** [barryclark/jekyll-now#155]
Hey Barry,

I forked this repo to build my site, and I noticed there is a class appended called "hoverZoomLink".  I have not been able to find where the class is in any of the assets.  When I hover on an image, it shows a really large image that is quite annoying.  Are you familiar with this?

**Comment by barryclark** [comment]
Hi @mkess-ivy, 

There's nothing called "hoverZoomLink" in Jekyll Now. Might be in some of the code that you added in?

**Comment by anthonytokosky** [comment]
For anyone else who finds this, the `hoverZoomLink` class is added by the Hover Zoom chrome plugin. 

[Hover Zoom](https://chrome.google.com/webstore/detail/hover-zoom/nonjdcjchghhkdoolnlbekcfllmednbl?hl=en)
