### ISSUE TITLE
username repeated in URLs?

### ISSUE THREAD

**Issue by benkoshy** [barryclark/jekyll-now#1553]
Hi all

I am seeing something curious:

The url is repeated: notice how we have: bkspurgeon.github.io repeated twice at the start of the URL?

Was wondering if anyone knew the cause and how to fix it? That would be very helpful.

https://bkspurgeon.github.io/BKSpurgeon.github.io/2019/12/19/getting-started-with-sequel-in-rails.html

rgds

Ben

**Comment by mindpower4** [comment]
hmm, seems you have set 'bkspurgeon.github.io' in your _config.yml as baseurl, i think you can leave it empty like this.. baseurl: "" as you're hosting the site on your user repository.

**Comment by benkoshy** [comment]
Excellent, that fixed it!
