### ISSUE TITLE
New page does not show in nav bar

### ISSUE THREAD

**Issue by ayaan-irshad** [barryclark/jekyll-now#1569]
I created a new page by creating a '100days.md' file in the root directory.

```
---
layout: page
title: 100 Days Of Code
permalink: /100days
---

### My daily log of the #100daysoffcode challenge.


```
The page does open up on typing in the url but there is no link of the page on the homepage navigation. How do I add that?

**Comment by bryantara** [comment]
@ayaan-irshad 

Go to: _layouts -> default.html
You can add your page manually after line 32

**Comment by ayaan-irshad** [comment]
> @ayaan-irshad
> 
> Go to: _layouts -> default.html
> You can add your page manually after line 32

Thanks
I got the link on the default homepage now, by doing what you said. But When I open the About homepage, I cant see the new page navigation again

**Comment by ayaan-irshad** [comment]
Thank you very much 😃.
