### ISSUE TITLE
Page Build Failure

### ISSUE THREAD

**Issue by awkwardtechdude** [barryclark/jekyll-now#159]
I wasn't able to troubleshoot, due to Jekyll issues on my Ubuntu 14.10 install.

The error email from GitHub is as follows:

>The page build failed with the following error:
>
>The file `style.scss` contains syntax errors. For more information, see >https://help.github.com/articles/page-build-failed-markdown-errors.

**Comment by barryclark** [comment]
You changed the config file to point to the wrong sass directory here: https://github.com/awkwardtechdude/awkwardtechdude.github.io/commit/916c1870cd7a115ec5eff1345aa69d3fb741b1d0#diff-aeb42283af8ef8e9da40ededd3ae2ab2R60

... so `style.scss` isn't able to import any of the sass partials.

What was the reason behind you doing that? I'd love to fix it if there was confusion somewhere.

**Comment by awkwardtechdude** [comment]
I'm sorry for wasting your time.

I had to reinstall Jekyll-Now, so I copied my config and posts and put them in the new install. I don't know why I ever changed that directory.

**Comment by barryclark** [comment]
No problem! Glad that Jekyll Now is useful :)

**Comment by awkwardtechdude** [comment]
I saw the problem and fixed it once you pointed out the file
