### ISSUE TITLE
Disqus threads for http and https sites separate

### ISSUE THREAD

**Issue by bewuethr** [barryclark/jekyll-now#165]
Is there a way to have the https site forward to the **http** site? I've just noticed that if people comment on a post reached using the **http** address and others do the same using the **https** address, the threads only show up on one or the other, as if there were two different sites.

Example: this post http://bewuethr.github.io/installing-fltk-133-under-visual-studio/ and the same under https, https://bewuethr.github.io/installing-fltk-133-under-visual-studio/, has two different comment threads.

**Comment by Koxzi95** [comment]
This is a possible solution:

https://gist.github.com/konklone/9968713

**Comment by bewuethr** [comment]
That's the exact problem, thanks @Koxzi95. I'll use that &ndash; maybe Jekyll Now could add it to the default template?

**Comment by Koxzi95** [comment]
It would depend on how the site is configured. For example I cannot access my site with: https://koxzi.me because of the hosting.

**Comment by bewuethr** [comment]
I don't use a custom domain name, so it should work, but good to know that it doesn't work with custom ones.

**Comment by barryclark** [comment]
Glad you got a fix for this, @bewuethr.

I'm confused as to why some people were going to an `https://` link on your site at all? I've never ran into that problem. Wondering if it's an issue that many people are having?
