### ISSUE TITLE
This icon though, do you even SVG?

### ISSUE THREAD

**Issue by deavmi** [barryclark/jekyll-now#181]
![](http://i.imgur.com/9Md6pS9.png)

**Comment by barryclark** [comment]
@deavmi The title of this is pretty rude and disrespectful to the person that put time into adding a YouTube icon to this project.

Open a PR if you'd like to update this icon to SVG.

**Comment by deavmi** [comment]
@barryclark Sorry that was d*ck of me, "Could you kindly please find the svg version of this icon please?" I am assuming this is an icon set. It seems to fit that set, surely it has an svg brother.

**Comment by deavmi** [comment]
@barryclark Found it, https://github.com/neilorangepeel/Free-Social-Icons/blob/master/Flat/SVG/YouTube.svg :smil

**Comment by eringrand** [comment]
Done. https://github.com/barryclark/jekyll-now/pull/183

**Comment by deavmi** [comment]
@barryclark @eringrand Thanks :smile: :wink:

**Comment by barryclark** [comment]
:heart: :sparkling_heart: :heart: :sparkling_heart: :heart: :sparkling_heart: :heart: :sparkling_heart:

**Comment by deavmi** [comment]
:heart:
