### ISSUE TITLE
two boxes

### ISSUE THREAD

**Issue by GitHub2021test** [barryclark/jekyll-now#1814]
Could anyone help me pls?
In fact I haven't changed any of the other code, I just wondered why there are two boxes (i just need one of them).
Thank you all
![two boxes](https://user-images.githubusercontent.com/80558979/111028255-c75e3c00-83f5-11eb-9c0c-cdc5e44742f0.PNG)
![code](https://user-images.githubusercontent.com/80558979/111028259-cd541d00-83f5-11eb-80c3-12d138206f1f.PNG)

**Comment by kuzand** [comment]
I have the same problem. How did you solve it?
