### ISSUE TITLE
Steps for adding new icon in footer

### ISSUE THREAD

**Issue by subhojit777** [barryclark/jekyll-now#184]
I want to add a new icon in footer and link it to a page. Could you please explain the steps.

**Comment by eringrand** [comment]
I've been working on a small "guide" to this. Look for it on the github wiki this weekend.

**Comment by barryclark** [comment]
Thanks, @eringrand!

**Comment by eringrand** [comment]
Here's the wiki [link](https://github.com/barryclark/jekyll-now/wiki/Adding-Icons)! It's not super complete, and I didn't check for typos as well as I probably should have... but all the information you need to get started should be there.

**Comment by subhojit777** [comment]
Thanks @eringrand

**Comment by subhojit777** [comment]
I have corrected the some typos, and have improved formatting. Thanks again @eringrand

**Comment by barryclark** [comment]
Awesome. Thanks @eringrand @subhojit777!
