### ISSUE TITLE
Using gh-pages branch in a non-user repo

### ISSUE THREAD

**Issue by rgerkin** [barryclark/jekyll-now#185]
Is there someway to use a regular repo (i.e. not one named username.github.io) via its gh-pages branch?  Like if I forked jekyll-now and renamed the default branch to gh-pages, and then created a new default branch to do other (non-web) stuff?  Would this work?

**Comment by eringrand** [comment]
It should, so long as you set up the config.yml file correctly.

**Comment by barryclark** [comment]
Yep. What Erin said :) I run www.jekyllnow.com and www.portfoliotips.co from regular repos.

Let us know if you run into any problems.
