### ISSUE TITLE
Hello, if I wanted to have a sort function how to do?

### ISSUE THREAD

**Issue by AllLuckly** [barryclark/jekyll-now#190]
Hello, if I wanted to have a sort function how to do?

**Comment by barryclark** [comment]
Would you be able to give a little more context? What are you trying to do?

**Comment by AllLuckly** [comment]
If I have a lot of articles, based on keyword classification, generates a classification page。

**Comment by barryclark** [comment]
There isn't really any support for something like that I'm afraid, Bison. You'd need to write it yourself, or search for a similar custom implementation that someone else has done and copy it over.
