### ISSUE TITLE
Page tab icon

### ISSUE THREAD

**Issue by omatt** [barryclark/jekyll-now#193]
Is there any way to add an icon to the browser tab?

**Comment by jaminscript** [comment]
What you're looking for is called a favicon. All you need is an image file ( the icon you want to use ) and a single line of HTML placed in the head section of your document to get it up and running.

**Comment by Azeez09** [comment]
Place the below line of code in head tag as suggested by @jaminscript.
Change the href and type attributes according your image type and its path
<pre>&lt;link rel="icon"  type="image/png"    href="http://example.com/myicon.png"&gt;</pre>

**Comment by omatt** [comment]
Where should I include it? I added 
```html
<link rel="icon" type="image/png" href="link.png">
```
to  ```/_layouts/post.html``` and it doesn't work. Maybe I'm missing something?

**Comment by jaminscript** [comment]
Add it to the head section of the _layouts/default.html file

**Comment by omatt** [comment]
Thanks. It now works. Maybe I should've asked on where to include the page tab icon in the first place.
