### ISSUE TITLE
extra SVG icons

### ISSUE THREAD

**Issue by FelipeRego** [barryclark/jekyll-now#201]
Hi there, first of all I'd like to say that Jekyll Now is a really cool platform. And it's so fast to get a blog up and running! Thanks for the great work! I've been slowly trying it out and it's been great. One thing I tried to include was an SVG icon for Quora in the blog but I could not find one. Was wondering whether there are any plans to include one sometime soon. Thanks again! Really great work!

**Comment by eringrand** [comment]
Hey - the wiki has a intro doc for how to add your own SVG icons onto your blog. https://github.com/barryclark/jekyll-now/wiki/Adding-Icons

Check it out and if you have any questions, let me know!

**Comment by barryclark** [comment]
Thanks, @eringrand! Would you like to be added as a contributor on the Jekyll Now repo?

**Comment by noxidsoft** [comment]
Had to unsubscribe from this thread, cause my inbox was receiving all the discussions recently, lol.

**Comment by eringrand** [comment]
Sure!

Erin Grand
Columbia University
MS Data Science (in progress)
University of Maryland
College of Computer and Natural Sciences
MS in Astronomy 2013
BS in Astronomy and Physics 2011
eringrand@gmail.com
