### ISSUE TITLE
generated pages not loading properly via custom domain ?

### ISSUE THREAD

**Issue by breathe67** [barryclark/jekyll-now#206]
Hello,

Thanks for your great work on the blog generator, which I'm now using as a template for my GitHub project blog. 

The pages load fine when I use the normal URL (breathe67.github.io/SketchCraft), but I'm running into a problem when I try to load it (redirected) from my custom URL (www.sketchcraft.org). Github support confirms I've set up the redirect properly,  and the main page does load,  but  the browser then fails to load other site files (e.g. style.css, see below). Have you encountered this before ? Note that I have modified the style.scss and _config.yml files for my own site, but don't think that should affect loading. 

Thanks, 
Chris

FYI, I took these steps: 
-------------------------------

1) added a CNAME record to github pages (www.sketchcraft.org)
2) removed the redirect from my DNS (godaddy.com) 
3) added a CNAME record at godaddy.com (host = "www", points to = "breathe67.github.io"

When I try to load www.sketchcraft.org in a browser, I do get my GitHub Pages content ...but the .CSS is not loaded. If I inspect the page source in my browser it says:

Failed to load resource: the server responded with a status of 404 (Not Found)                  http://www.sketchcraft.org/SketchCraft/style.css

**Comment by Koxzi95** [comment]
Could you link your config?

**Comment by Theby** [comment]
Or the whole repository?

**Comment by breathe67** [comment]
Hi,

I'm assuming this mail is about my note a few weeks ago re my Github Jekyll
site not loading properly via http://www.sketchcraft.org/

If so, my jekyll repo is:
https://github.com/breathe67/SketchCraft/tree/gh-pages

Please note that since my note I have added some redirection to my site
(registered via godaddy.com), just to see if it would magically fixed the
page loading - it didn't.)

Thanks,
Chris

**Comment by Koxzi95** [comment]
That link 404s. It's not private is it?

**Comment by breathe67** [comment]
sorry, I thought the gh-pages repo might be public: I will try to send a
zip file, but here's the _config.yml:

## This file contains configuration flags to customize your site# # Name of
your site (displayed in the header)name: SketchCraft # Short bio or
description (displayed in the header)description: Dynamic Sketching # URL
of your avatar or profile pic (you could use your GitHub profile pic)avatar:
https://avatars.githubusercontent.com/breathe67 #
https://raw.githubusercontent.com/breathe67/jekyll-now/master/images/jekyll-logo.png
## Flags below are optional# # Includes an icon in the footer for each
username you enterfooter-links: dribbble: email: facebook:
chris.chan.3958914 flickr: github: instagram: linkedin: pinterest: rss: #
just type anything here for a working RSS icon, make sure you set the "url"
above! twitter: breathe67 stackoverflow: # your stackoverflow profile, e.g.
"users/50476/bart-kiers" youtube: # channel/<your_long_string> or
user/<user-name> googleplus: # anything in your profile username that comes
after plus.google.com/ # Enter your Disqus shortname (not your username) to
enable commenting on posts# You can find your shortname on the Settings
page of your Disqus accountdisqus: # Enter your Google Analytics web
tracking code (e.g. UA-2110908-2) to activate trackinggoogle_analytics: #
Your website URL (e.g. http://barryclark.github.io or
http://www.barryclark.co)# Used for Sitemap.xml and your RSS feedurl: # If
you're hosting your site at a Project repository on GitHub pages# (
http://yourusername.github.io/repository-name)# and NOT your User
repository (http://yourusername.github.io)# then add in the baseurl here,
like this: "/repository-name"baseurl: "/SketchCraft" ## !! You don't need
to change any of the configuration flags below !!# markdown: redcarpet
highlighter: pygmentspermalink: /:title/ # The release of Jekyll Now that
you're usingversion: v1.1.0 # Set the Sass partials directory, as we're
using @importssass: style: :expanded # You might prefer to minify using
:compressed # Use the following plug-insgems: - jekyll-sitemap # Create a
sitemap using the official Jekyll sitemap gem # Exclude these files from
your production _siteexclude: - Gemfile - Gemfile.lock - LICENSE - README.md -
CNAME

**Comment by breathe67** [comment]
Here's a .zip of the site...

**Comment by Koxzi95** [comment]
For this I believe it isn't built to be hosted on the gh-pages branch (do feel free to correct me if I'm wrong on that).

**Comment by breathe67** [comment]
Not sure what you mean... As far as I know, Jekyll is specifically meant
for GitHub Pages' hosted sites, according to its author.

I followed the 'Jekyll' site generator's instructions for setting it up.
It's possible I misread something, but it is suppose to be for
Github-hosted sites, which are specifically supposed to be on the gh-pages
branch.

**Comment by Theby** [comment]
it's supposed to be on the gh-pages when you do a a Project Site, but if you are doing an user or organization site you must use the master branch
https://pages.github.com/

**Comment by breathe67** [comment]
It *is* a project site. The project is private, the pages site is public.

**Comment by barryclark** [comment]
@breathe67, make sure you've followed these lines correctly https://github.com/barryclark/jekyll-now/blob/master/_config.yml#L42-L50

From inspecting markup on http://www.sketchcraft.org/ that appears to be the issue.
