### ISSUE TITLE
How can I add sharing buttons to my posts?

### ISSUE THREAD

**Issue by reyn4rd** [barryclark/jekyll-now#209]
Hi!

I want to know how can I add sharing buttons to my blog posts.

Thanks.

**Comment by Koxzi95** [comment]
You can add a basic share 'bar' anywhere in your page. 

Quite a simple guide here:

 http://codingtips.kanishkkunal.in/share-buttons-jekyll/

**Comment by reyn4rd** [comment]
Thanks, helped me :+1:

**Comment by Koxzi95** [comment]
@reyn4rd Glad to hear it :octocat:
