### ISSUE TITLE
How do I create static, non-blog pages?

### ISSUE THREAD

**Issue by onebree** [barryclark/jekyll-now#215]
I would like some pages in addition to the blog posts. (Maybe like about, skills, a portfolio). Right now, my repository is set as a user-based GH page. I see that in `_config.yaml` that `baseurl` is only suggested if the Page is a Project repository.

I would ideally, in time, like to keep my github domain, but dedicate Jekyll posts to `onebree.github.io/blog`. What do you recommend that I do?

BTW thank you for producing this repository. It will help me so much.

**Comment by Koxzi95** [comment]
You can have static pages similar to the 'About' Page: https://github.com/Koxzi95/koxzi95.github.io/blob/master/about.md

**Comment by dguido** [comment]
@barryclark looks ok to close this!

**Comment by izulien** [comment]
@Koxzi95 I've tried this with a file I named `resources.md` in the root of my `master` branch (right next to `about.md`) and I'm not getting this to work at all.  Do I need to name this file similar to blog posts and place it in the `_posts` directory?
