### ISSUE TITLE
A problem- I can't set up the website

### ISSUE THREAD

**Issue by yjssee2** [barryclark/jekyll-now#217]
![image](https://cloud.githubusercontent.com/assets/12966197/8254367/6e0d5274-16ca-11e5-9241-52bbfca6aa55.jpg)
![image](https://cloud.githubusercontent.com/assets/12966197/8254368/6e5e7ba4-16ca-11e5-8418-bdb50e2ba23b.jpg)
I can't set up the website after forking the program and renaming my name, how can I solve this problem?
Thank you.

**Comment by Koxzi95** [comment]
This is quite strange. Have you since verified your email?

**Comment by yjssee2** [comment]
Thank you, I got it!  I recieve the email from github just now, I recieve the email from github just now. orz

**Comment by nhajiyani** [comment]
@yjssee2 Do you still have this issue or is it okay to close this?

Thanks.

**Comment by dguido** [comment]
@barryclark looks ok to close this!
