### ISSUE TITLE
jemoji

### ISSUE THREAD

**Issue by donavon** [barryclark/jekyll-now#227]
Why was support for [jemoji](https://github.com/jekyll/jemoji) dropped, and can we have it back?

I see the commit where it was removed (https://github.com/barryclark/jekyll-now/commit/79744a7fbfff17985377da0c9a04c89d4f2e12e9), but really no explanation as to why.

See fork at https://github.com/donavon/donavon.github.io/blob/master/_posts/2014-3-3-Hello-World.md

**Comment by Koxzi95** [comment]
Does it still work if you add it to your version?

**Comment by donavon** [comment]
Well... sort of. In the full view(http://donavon.github.io/Hello-World/), I see this (escaped html):
![image](https://cloud.githubusercontent.com/assets/887639/8607222/71883c94-265f-11e5-8c2b-ca407dedadc9.png)

And in the excerpt view (http://donavon.github.io/), I see this (markdown text):
![image](https://cloud.githubusercontent.com/assets/887639/8607242/a50615e6-265f-11e5-83c3-11ef7eb9657d.png)

**Comment by ellivr** [comment]
Was wondering for this as well, so why emotes removed? It is certainly a feature that most of people would use.

**Comment by barryclark** [comment]
I removed jemoji because it was buggy.

Things like Pocket, Twitter, and screen readers continually treated the `<img>` like it was a actual post content, and would often use it in post previews which looked reeeallly amateur.
