### ISSUE TITLE
Adding pluggins to Jekyll Now?

### ISSUE THREAD

**Issue by benpetersen** [barryclark/jekyll-now#235]
How does one add plugins to Jekyll Now? 

I have added _plugins/jekyll-sitemap.rb and a gem: jekyll-sitemap, but this doesn't make a sitemap.xml, do I have to build the project locally via Ruby and RubyGems or is there an easier way.

**Comment by barryclark** [comment]
I remember this one getting answered via Twitter. Any additional questions, Ben?
