### ISSUE TITLE
code highlight for backtick(`)

### ISSUE THREAD

**Issue by ttddyy** [barryclark/jekyll-now#252]
The `<code/>` tag generated by backtick ( \` ) is not highlighted.
It would be great that they are also get highlighted as github wiki does like `this`.

Thanks,

**Comment by rajohns08** [comment]
+1

**Comment by barryclark** [comment]
I believe this is a Jekyll issue, covered here: https://github.com/jekyll/jekyll/issues/2709 rather than something that can be fixed in Jekyll Now.

**Comment by barryclark** [comment]
Oh snaps, this works now!

https://github.com/barryclark/jekyll-now/commit/8c8154bc9cdfb4cba19f1f3a3eba05b602a70ccd

:sparkles:
