### ISSUE TITLE
can not parse markdown node to html 

### ISSUE THREAD

**Issue by Kyson** [barryclark/jekyll-now#259]
like delete ~~~del me~~~
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

**Comment by barryclark** [comment]
I don't get it. Could you explain the problem you're running into, and what you're expecting to happen?

**Comment by Kyson** [comment]
i have resolve this problem , just add following string:

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "superscript"]

to _config.yml

anyway,thx a lot for your reply.

**Comment by barryclark** [comment]
:+1:
