### ISSUE TITLE
There is no Disqus 'short name' listed in settings page of disqus

### ISSUE THREAD

**Issue by rajohns08** [barryclark/jekyll-now#265]
I have added my username since there is no short name in settings page, but my blog says "We were unable to load Disqus."

**Comment by rajohns08** [comment]
I have added my username since there is no short name in settings page, but my blog says "We were unable to load Disqus."

**Comment by barryclark** [comment]
https://help.disqus.com/customer/portal/articles/466208

**Comment by rajohns08** [comment]
ok got it, thanks. might be worth mentioning in readme
