### ISSUE TITLE
Why doesn't code syntax highlighting match Github?

### ISSUE THREAD

**Issue by rajohns08** [barryclark/jekyll-now#266]
View my jekyll-now blog poser here: http://rajohns08.github.io/id-instancetype/

And the repo file on github: https://github.com/rajohns08/rajohns08.github.io/blob/master/_posts/2014-11-22-id-instancetype.md

Github repo view seems to do a better job of the code syntax highlighting. Check the 

```objc
[[Dog giveMeAnimalC] makeSound];
```

block for example. Also, single backtick lines don't have the different background color on my jekyll-now blog.

**Comment by barryclark** [comment]
Because Jekyll Now doesn't render markdown identically to GitHub.

If you find out a better way to rock syntax highlighting then contributing it back would be much appreciated.

**Comment by rajohns08** [comment]
Ok gotcha, yeah I don't have any clue about this kind of stuff. I was just asking in case there was a quick config settings item I could change to make it match Github.

**Comment by barryclark** [comment]
I wish there was, I found it pretty tricky :)
