### ISSUE TITLE
How to upgrade the jekyll of your forked repository

### ISSUE THREAD

**Issue by shanalikhan1** [barryclark/jekyll-now#270]
Hi , i forked your repo and make a blog
I want to know how to upgrade the jekyll in my github repo to latest version of jekyll without losing my settings.

**Comment by barryclark** [comment]
Hey @shanalikhan1,

This is a step that needs to be done locally on your machine.

You need to merge from upstream (my repo). Here are some instructions - https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

Alternatively, you could clone or save the latest jekyll-now code to your local machine, and manually overwrite all of the template files and things with the new files. Leaving your /_posts/ in tact.

Let me know if you have any further questions.

Cheers,
Barry
