### ISSUE TITLE
how to add tag function?

### ISSUE THREAD

**Issue by Kyson** [barryclark/jekyll-now#284]
hi

i want to use tag .

when i add head as following:

layout: post
title: markdown sth
published: true
tags: [test,markdown]

i want have a tag page which show all tags and link to relational articles

how could i get it?

thx a lot

**Comment by barryclark** [comment]
A couple of other folks have implemented tags in the past. Check 'em out:

- https://github.com/barryclark/jekyll-now/pull/130
- https://github.com/barryclark/jekyll-now/pull/186

Cheers,
Barry
