### ISSUE TITLE
_includes/svg-icons.html

### ISSUE THREAD

**Issue by prodicus** [barryclark/jekyll-now#288]
Hey Barry, 

Actually, the linkedin link to someone's profile in the svg-items.html is 

```html
{% if site.footer-links.linkedin %}<a href="https://www.linkedin.com/in/{{ site.footer-links.linkedin }}"><i class="svg-icon linkedin"></i></a>{% endif %}
```

Now when I forked your repo and added my link for linkedin in _config.yml . It was something like 
```yml
linkedin: tasdik-rahman/6a/364/56b
```

So the end link in the footer was like https://www.linkedin.com/in/tasdik-rahman/6a/364/56b

If you click it, it shows a page not found error.

I changed /in/ to /pub and it seemed to work(in my case). https://www.linkedin.com/pub/tasdik-rahman/6a/364/56b

So I made a change to svg-icons.html to have something like this
```html
{% if site.footer-links.linkedin %}<a href="https://www.linkedin.com/in/{{ site.footer-links.linkedin }}"><i class="svg-icon linkedin"></i></a>{% endif %}
```
Just wanted to let you know. I don't know how do I make a pull request for that particular commit (if this makes one) so I thought I could just say a hi here :D

**Comment by cjerrington** [comment]
you can also change your Linkedin profile link to the /in/{{username}}. This is preferred too since you do not have the random string after your username. It looks nicer too on resumes! 

https://help.linkedin.com/app/answers/detail/a_id/87/~/customizing-your-public-profile-url

**Comment by barryclark** [comment]
Yea, like @cjerrington mentioned. This assumes that you're changing your LinkedIn profile link, which does look a lot nicer!
