### ISSUE TITLE
Replace feed.xml with new jekyll-feed plugin

### ISSUE THREAD

**Issue by dguido** [barryclark/jekyll-now#292]
https://github.com/blog/2053-easier-feeds-for-github-pages

**Comment by urda** [comment]
Here's what I did:

1) Set the `footer-links` `rss` as follows to get the `rss` link to show in the footer:
```yml
rss: jekyll-feed
```

2) Then add the `jekyll-feed` to your config:
```yml
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed
```

3) Delete `feed.xml` from the root of the repository.

4) Build your `jekyll-now` powered pages. A `feed.xml` should be generated using the `jekyll-feed`.

5) Enjoy!

**Comment by barryclark** [comment]
Sweet. Let's move to `jekyll-feed` as you guys said. It's supported by `github-pages` yay!

I don't suppose either of you guys would fancy submitting a PR for this?

Would be much appreciated.

**Comment by barryclark** [comment]
Done!
