### ISSUE TITLE
files not running on local syestem after cloning

### ISSUE THREAD

**Issue by rajiv-shrivastava** [barryclark/jekyll-now#293]
As after cloning the repository files are unable to run on http://localhost:4000/ even after insatlling jekyll sucessfully. Then just run this command gem install jekyll-sitemap.

This is the solution for the problem

**Comment by barryclark** [comment]
I'd guess you installed Jekyll, rather than `gem install github-pages` https://github.com/barryclark/jekyll-now#local-development
