### ISSUE TITLE
How would I create permalink in heading

### ISSUE THREAD

**Issue by subhojit777** [barryclark/jekyll-now#297]
We can generate headings by `#`, `##`, `--------`, etc. Is there any way we can generate permalinks of them? Github adds a permalink for every title, does Jekyll provides similar feature

**Comment by barryclark** [comment]
Hey @subhojit777,

That's a feature of the markdown engines, that can often be enabled in `_config.yml` in Jekyll. If I remember rightly, I don't think redcarpet does it, but kramdown does - http://kramdown.gettalong.org/syntax.html would be a good place to look... and search "kramdown" on this page - http://jekyllrb.com/docs/configuration/

Cheers,
Barry

**Comment by subhojit777** [comment]
Thanks. Instead of generating this, I created the permalinks manually. Anyone looking for a workaround (like me) can refer this StackOverflow answer http://stackoverflow.com/a/7335259/57171

**Comment by barryclark** [comment]
Nice, thanks @subhojit777!
