### ISSUE TITLE
Localisation?

### ISSUE THREAD

**Issue by frankmeeuwsen** [barryclark/jekyll-now#308]
Hi

Would it be possible to make Jekyll Now localized in other languages? I could help translate it in Dutch if you want to.

**Comment by barryclark** [comment]
It's one of those things that would be lovely, but I don't have the time to get around to... and also don't know how to do without making the repo a lot more complex.

Haven't had toooo many requests for it either.

**Comment by barryclark** [comment]
Gonna close this, as there haven't been any requests, but thanks for the offer @frankmeeuwsen!
