### ISSUE TITLE
Adding home page

### ISSUE THREAD

**Issue by PixelPaper** [barryclark/jekyll-now#322]
Hi Barry,

Just wondering if it would be possible to easily change the *index.html* page to a static, introductory home page and move the blog to another one such as *blog.html*. 

I would like to use an amended version of this to get my first year IxD students quickly online and blogging without the need to host their own site (this will come later).

Best,

Paul

**Comment by barryclark** [comment]
Yep, Paul. You can just that. Just copy the current contents of index.html to blog.html, then put your static homepage at index.html.

**Comment by PixelPaper** [comment]
Brilliant, thanks Barry. 

Appreciate the speedy reply.

Paul



 <http://www.ulster.ac.uk/>
Paul McCormack
FHEA FCHERP
Lecturer in Interaction Design
Course Director BDes Hons Interaction Design
T: 028 9536 7342
E: p.mccormack@ulster.ac.uk <mailto:p.mccormack@ulster.ac.uk> W: www.ulster.ac.uk <http://www.ulster.ac.uk/>
Social: @ElevenThirty <ttps://twitter.com/ElevenThirty>
