### ISSUE TITLE
How do I change the format so that it looks exactly like the format in Github?

### ISSUE THREAD

**Issue by pong-pantola** [barryclark/jekyll-now#350]
I planned to use Github to host tutorials I'm creating.  I like how my markdown files are formatted in Github.  However, I don't want the features for code sharing (e.g., Fork Button) to appear since I'm using it more of a Blog rather than as a code repository.

I recently discovered Gitpages and saw that I can quickly create one using Jekyll Now.  I'm able to transfer my tutorial to my Gitpages using Jekyll Now.  However, the format of the blog is not the same if compared to viewing the same markdown file using Github.  

I think it has something to do with templates.  But I have no idea on how to configure the _config.yml file so that my Gitpage will have the same format has Github.

May I request your assistance on this?

Attached are the screenshot of my Blog in github (the format I like) and the one in gitpage (the format is wrong but I want to use this because it removes the unnecessary buttons that appear in Github).
![screenshot of tutorial in github](https://cloud.githubusercontent.com/assets/16174815/11737939/2e722d64-a019-11e5-8f81-fac9c9990b51.JPG)
![screenshot of tutorial in gitpage](https://cloud.githubusercontent.com/assets/16174815/11737940/2e82db50-a019-11e5-9e91-2a7643071f8d.JPG)

Thanks.

alexis

**Comment by benpetersen** [comment]
First point on *code sharing*, if it's hosted on github, it's sharable. However, you can create private repositories, but there is a charge per month for that. 

Second point on formatting, you have a couple options. Build a widget and use custom CSS or use [Github Gits](https://demisx.github.io/jekyll/2014/01/13/improve-code-highlighting-in-jekyll.html) but keep in mind, everything Jekyll does, Jekyll Now does not.
