### ISSUE TITLE
How can I use Chinese to write description in _config.yml?

### ISSUE THREAD

**Issue by Warnier-zhang** [barryclark/jekyll-now#351]
When I tried this, I got a build error.

**Comment by Warnier-zhang** [comment]
Using encoding:utf-8 may help. But I can't use Chinese when writing a  post.

**Comment by angerhang** [comment]
I think you can use utf-8 to write a post in Chinese.
```
MacBook-Pro:_posts yuancalvin$ file -I 2015-12-13-test.md
2015-12-13-test.md: text/plain; charset=utf-8
MacBook-Pro:_posts yuancalvin$ cat 2015-12-13-test.md 
---
layout: post
title: test 
---

这是一篇测试的文档
```

I can do it without any problem : ) 
Hope this will help.

<img width="1430" alt="screen shot 2015-12-16 at 16 20 05" src="https://cloud.githubusercontent.com/assets/7655454/11844803/e71637d4-a410-11e5-9ffb-657ba4da382c.png">

**Comment by Warnier-zhang** [comment]
Thank for help. I find that it was the encoding error that cause the issue.
