### ISSUE TITLE
Lack of feed.xml file

### ISSUE THREAD

**Issue by cesards** [barryclark/jekyll-now#370]
I don't know if it existed before or not, but this line https://github.com/barryclark/jekyll-now/blob/master/_layouts%2Fdefault.html#L13 makes me think either it's a useless file and we need to remove that line from the `default.html` or the file was removed unintentionally.

But I got this from my old Jekyll blog repository,. I forked this project so maybe is outdated, but if we need this I could make a PR with the file:

```xml
---
layout: null
---

<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>{{ site.name | xml_escape }}</title>
    <description>{{ site.description | xml_escape }}</description>
    <link>{{ site.url }}</link>
    <atom:link href="{{ site.url }}/feed.xml" rel="self" type="application/rss+xml" />
    {% for post in site.posts limit:10 %}
      <item>
        <title>{{ post.title | xml_escape }}</title>
        <description>{{ post.content | xml_escape }}</description>
        <pubDate>{{ post.date | date: "%a, %d %b %Y %H:%M:%S %z" }}</pubDate>
        <link>{{ site.url }}{{ post.url }}</link>
        <guid isPermaLink="true">{{ site.url }}{{ post.url }}</guid>
      </item>
    {% endfor %}
  </channel>
</rss>
```

I have found this commit https://github.com/barryclark/jekyll-now/pull/343/files, so maybe we should remove that line...

**Comment by purana** [comment]
I noticed that the feed.xml is built, when you populate the required information in the _config.yml, but it makes the feed.xml contain ALL posts. In a large blog site, this makes for a huge feed.xml file. The proposed change above would limit feed.xml to 10 posts, which would be a good idea. I tried to submit a pull request for the same thing. But I am only new to github usage and I think i screwed up. Please commit the change above, as this addresses the fault.

**Comment by barryclark** [comment]
feed.xml gets generated by the jekyll-feed gem here https://github.com/barryclark/jekyll-now/blob/master/_config.yml#L78
