### ISSUE TITLE
readmore 

### ISSUE THREAD

**Issue by smnmtzgr** [barryclark/jekyll-now#379]
Hello,

when exactly is the READMORE link of a blog post generated? Do I have to insert a new line after my first sentence of the post?

What is the trigger for the creation of the READMORE link?

Regards,
Simon

**Comment by benpetersen** [comment]
Read More links can be anywhere, but you have to insert a link. Below is how I use it on my homepage 

index.html
`
---
layout: default
---

<div class="posts">
  {% for post in site.posts %}
    <article class="post">

      <h1><a href="{{ site.baseurl }}{{ post.url }}">{{ post.title }}</a></h1>

      <div class="entry">
        {{ post.content | strip_html | truncatewords: 50 }}
      </div>

      <a href="{{ site.baseurl }}{{ post.url }}" class="read-more">Read More</a>
    </article>
  {% endfor %}
</div>
`

**Comment by barryclark** [comment]
Thanks for the answer Ben!
