### ISSUE TITLE
CSS instead of Sass

### ISSUE THREAD

**Issue by davidcafor** [barryclark/jekyll-now#381]
Hi Barry,

Thanks for your great work. I've finally installed Jekyll on my Github Page but I've got a question for you.
Is there any way to use CSS instead of SASS? if the answer is yes, how can I do that?

Thanks!

**Comment by sarunast** [comment]
Just don' use it. Create a new file style.css in root and you're good.

**Comment by benpetersen** [comment]
CSS and SCSS are very similar, basically write SCSS with levels of css queries. Learn the syntax and just modify the existing style.scss, otherwise you'll have to find a way to build css files into scss locally. Definitely do-able, but learning syntax is just about the same amount of work

**Comment by barryclark** [comment]
Thanks for the answers @sarunast and @benpetersen!
