### ISSUE TITLE
BrowserSync reloading + scss injecting

### ISSUE THREAD

**Issue by sarunast** [barryclark/jekyll-now#382]
I managed to implement BrowserSync ( live reloading + css injecting) by using gulp. I am not sure if you are interesting adding it to the project.

This is the link to gulp file (gulp):
https://github.com/sarunast/sarunast.github.io/blob/master/gulpfile.js

Feel free to close this if you think that there is no need for this, otherwise let me know I will make a proper pull request.

**Comment by barryclark** [comment]
Thanks Sarunas. I can see how this would be super helpful for local dev. Seeing as Jekyll Now is more about bypassing doing local dev and letting GitHub Pages do that work I'll pass on including another file. 

Thanks though!
