### ISSUE TITLE
how to make code highlights  by adding a code block  like ?

### ISSUE THREAD

**Issue by donganwangshi** [barryclark/jekyll-now#40]
I use '''
```
somecode 

```
and 
```xml
some xml'codes
```
but it not works

**Comment by barryclark** [comment]
@donganwangshi There are a number of ways around this. I'd probably just recommend not displaying the first X characters of a post as a preview, if it causes this problem. You could not display a post preview at all, or use  tags instead before or after the code excerpt. Or you could have a metadata for your posts for your excerpt and use that as the post preview instead. 

There are a few ways around it. Let me know if it's still a problem and you need any additional help/info.
