### ISSUE TITLE
_Config.yml markdown deprecating redcarpet, update to kramdown

### ISSUE THREAD

**Issue by benpetersen** [barryclark/jekyll-now#406]
The default markdown in _config.yml needs be updated to kramdown

Below is an email I receive every time a page is loaded: 
The page build completed successfully, but returned the following warning:

You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions you can contact us by replying to this email.

**Comment by cesards** [comment]
You could make a Pull Request and update the issue by yourself. You just have to change a line of code ^^
```
markdown: kramdown
```

:+1:

**Comment by urda** [comment]
This isn't enough, I also suggest the highlighter gets updated too. Here's a sample of what I had to do on my install to get everything just right:

```diff
diff --git a/_config.yml b/_config.yml
index a41b5a3..ad7ee04 100644
--- a/_config.yml
+++ b/_config.yml
@@ -56,8 +56,14 @@ baseurl: ""
 # !! You don't need to change any of the configuration flags below !!
 #
 
-markdown: redcarpet
-highlighter: pygments
+markdown: kramdown
+
+kramdown:
+  input: GFM
+  hard_wrap: false
+
+highlighter: rouge
+
 permalink: /blog/:year/:month/:day/:title
```

See my full changes at: https://github.com/urda/website/commit/fe055f4f3717c7947421b04b51f80ece7efa7dda

**Comment by cesards** [comment]
You're right. i'm not also sure about this move from Github. I had a bunch of html code in my markdowns and now it's not working. I've had a look in StackOverflow and  I found nothing helpful at all...

**Comment by barryclark** [comment]
Fixed by https://github.com/barryclark/jekyll-now/pull/445

See https://github.com/barryclark/jekyll-now/commit/8c8154bc9cdfb4cba19f1f3a3eba05b602a70ccd for how to update your `_config.yml`.

My changes are similar to @urda's. Just changing the CSS class added so that the existing syntax highlighting styles still work too.

**Comment by ireaneus** [comment]
I am having problems just getting tables markdown in github pages to work with Jekll themes, here is my _config.yml . 

theme: jekyll-theme-hacker
title: Welcome to Ireaneus Linux Cheat Sheets webpage
Description: Linux Commandline cheatsheets with valuable examples 
url: https://ireaneus.github.io/linux-cheat-sheets/
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

my markdown is just the README.md
Column 1 | Column2
--------- | ---------
