### ISSUE TITLE
Setting up Octopress on github pages without the command line

### ISSUE THREAD

**Issue by ishu3101** [barryclark/jekyll-now#424]
Since [Octopress][1] is a wrapper around Jekyll, is it possible to set up a octopress blog on github pages without touching the command line.

[1]: http://octopress.org

**Comment by barryclark** [comment]
I'm not sure, not dug into Octopress too much. If you find out, I'd love to know :)

**Comment by ishu3101** [comment]
If you could write a tutorial on how to take a normal jekyll blog (which requires setting up a local development environment) and turn into a blog like jekyll-now (which does not require setting up a local development environment) that would be appreciated.

I have tried setting up octopress like jekyll-now at https://github.com/ishu3101/octopress but I get this error message when I deploy it on github pages. It works fine on my local machine though.

```
The page build failed with the following error:
 
The tag `include_array` on line 33 in `_layouts/post.html` is not a recognized Liquid tag.
```
