### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by deniz946** [barryclark/jekyll-now#432]
Hello, forked it, changed the name to http://deniz946.github.io/, tried to access, and nothing, error 404. Okay. Tried Step 2, edited config.yml, tried again to go http://deniz946.github.io/ and still 404, any help please?

**Comment by kedarjoyner** [comment]
I have the exact same issue. And you can't fork your own repositories - are you cloning?

**Comment by mahongliang** [comment]
you forget to modify the CNAME file as `example.com`

**Comment by barryclark** [comment]
Holler back if you're still having problems.

**Comment by aborruso** [comment]
Hi @mahongliang and @barryclark  I have the same error for http://albopop.it/

The repo is https://github.com/aborruso/albo-pop e the CNAME file is https://github.com/aborruso/albo-pop/blob/gh-pages/CNAME

It's impossible to render my 404 page. What's wrong?

Thank you

**Comment by barryclark** [comment]
@aborruso you need to name the repo aborruso.github.io

**Comment by aborruso** [comment]
Hi @barryclark  is there no way to use 404.md file for a repo different from username.github.io?

Thank you very much

**Comment by barryclark** [comment]
Oh, I see. You're using a different repo and the gh-pages branch.

Try uncommenting this line in your config? https://github.com/aborruso/albo-pop/blob/gh-pages/_config.yml#L50

**Comment by aborruso** [comment]
@barryclark I have made but it destroy the path to my CSS, images, ecc.

The actual URL is http://albopop.it your great repo works, and in example the path of my images folder is http://albopop.it/images/

If I uncomment that line the path becomes http://albopop.it/albo-pop/images/ and it's not a correct path.

Thank you
