### ISSUE TITLE
Site content is not changing

### ISSUE THREAD

**Issue by kirishikikaito** [barryclark/jekyll-now#450]
I have edited _config.yml as suggested in step 2 of README, but nothing happened.
Could you help me?

Here's my repo: https://github.com/kirishikikaito/kirishikikaito.github.io/blob/master/_config.yml

P.S. I'm newbie at GitHub and this is my first issue (and repo)

**Comment by romach** [comment]
@kirishikikaito first of all you have errors in your `_config.yml` (lines 21, 22, 25, 26, 29, 37): `:` separators must be followed by a space before the value. So, for example, line `email:kirishikikaito@gmail.com` must be `email: kirishikikaito@gmail.com`.

Second, put `""` to `baseurl:` parameter. So it will be: `baseurl: ""`

**Comment by kirishikikaito** [comment]
Thank you so much! Now it works)
