### ISSUE TITLE
Autolink in kramdown?

### ISSUE THREAD

**Issue by jleclanche** [barryclark/jekyll-now#459]
In redcarpet, Jekyll Now enabled the autolink extension by default which was really useful. I can't find a way to enable it for kramdown, though. Any ideas?

**Comment by jleclanche** [comment]
So apparently kramdown's autolink is enabled by default but its syntax is different and the url must be enclosed in braces.

**Comment by smokingun** [comment]
Square brackets, more precisely:
http://kramdown.gettalong.org/syntax.html#automatic-links
(in case somebody finds this topic)

**Comment by iBobik** [comment]
Is it possible to configure Kramdown to detect link without braces?

Like there on GitHub: http://example.com

**Comment by mrmanc** [comment]
> … the url must be enclosed in braces.

I think the [Kramdown automatic links syntax](https://kramdown.gettalong.org/syntax.html#automatic-links) is angle brackets, rather than braces, like this: `<https://github.com/barryclark/jekyll-now/issues/459>`.

**Comment by zimbatm** [comment]
Why is Kramdown claiming to be GFM-compatible if the autolinking doesn't work the same way

**Comment by noraj** [comment]
Can we re-open this ?

> Why is Kramdown claiming to be GFM-compatible if the autolinking doesn't work the same way

```yaml
kramdown:
  input: GFM
```

The GFM compatibility is a lie, kramdown has its own syntax.

> Is it possible to configure Kramdown to detect link without braces?

Can you add an option to remove the need of angle brackets if you don't want to do it the default behavior? So it will be compatible with commonMark, GFM, etc. pretty 99% of markdown parser other than the strict original ones which don't have autolinks or table, or any extension.

**Comment by drscotthawley** [comment]
This is a desirable feature.  This should be reopened.
