### ISSUE TITLE
Main page - description in search

### ISSUE THREAD

**Issue by VadymVolos** [barryclark/jekyll-now#520]
Hi!
My description in search:
>Welcome to GitHub Pages. This automatic page generator is the easiest way to create beautiful pages for all of your projects

But I want my text was. How to do it?
Thanks!

**Comment by cjerrington** [comment]
you change that in the ```_config.yml``` file. Looks like you figured this out too: ```description: Маркетолог со стажем```

If so, you can close this issue.

**Comment by VadymVolos** [comment]
Thanks!
