### ISSUE TITLE
cannot type the brackets or colon in the post's title

### ISSUE THREAD

**Issue by hsuyh** [barryclark/jekyll-now#522]
I want to type the brackets [ ] or colon :  in the post's title

for example:
in _posts/2016-5-10-test.md

```ruby
---
layout: post
title: [test] report1
---
...
```

but the github will email me say page build error with following messages
>There was a YAML syntax error on line 2 column 1 in `<unknown>`: `did not find expected key while parsing a block mapping`. For more information, see https://help.github.com/articles/page-build-failed-invalid-yaml-in-data-file.

Any setting I have to change so that I can type the bracket or colon in the title?
thank you!

**Comment by cjerrington** [comment]
the [ brackets ] like so are part of markdown within GitHub and Jekyll.There may need to be another way you want to format your titles. 

The [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) starting at the Links section might help you understand why this is happening. It picks the [ test ] as a link and cannot find the URL to associate it. I hope this helps.

**Comment by hsuyh** [comment]
@cjerrington  thank you!
