### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by holmeslinux** [barryclark/jekyll-now#536]
hi all,
i wonder how can i add a favicon.
thank...

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
solved!
default.html edited the file and add two parameters to see:

==============================
<!DOCTYPE html>
<html>
  <head>
    <title>{% if page.title %}{{ page.title }} – {% endif %}{{ site.name }} – {{ site.description }}</title>

    {% include meta.html %}

    

    <link rel="stylesheet" type="text/css" href="{{ site.baseurl }}/style.css" />
    <link rel="alternate" type="application/rss+xml" title="{{ site.name }} - {{ site.description }}" href="{{ site.baseurl }}/feed.xml" />
    
    **<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?">**

    <link href='//fonts.googleapis.com/css?family=Lato:400,700|Raleway:400,700|Comfortaa:700' rel='stylesheet' type='text/css'>

    

    **
    
      <link rel="shortcut icon" href="images/favicon.ico">**
            </head>
==============================

add the favicon.ico file in user.github.io.
ready!

vlw fwi, Holmes :)

**Comment by fallenskillz** [comment]
I just noticed this @holmeslinux , good you got it.

**Comment by cjerrington** [comment]
@holmeslinux since you got this solved, could you close the issue? I don think this would be something @barryclark could like to add since not every user will have a favicon to add to their site and other wise may cause issues. Even though we could do an ```if favicon then show it``` kind of check. That would be up to Barry Clark.

**Comment by holmeslinux** [comment]
ok, close!
thank...

vlw fwi, Holmes :)

**Comment by interglobalmedia** [comment]
I think it would be a great thing to implement in Jekyll. Favicons are free and easy to create! gh-pages is always looking for one! Anyway, thanks @holmeslinux for sharing your discovery!

**Comment by 2E0PGS** [comment]
@holmeslinux Thanks so much for that. I spent a while trying to add it but realised I must place it in the default.html so I had to clone the default.html from the theme I am using and place it in the _layouts folder then appending the line to add the favicon. Finally placing the favicon.ico in the root of the repo.

**Comment by gocs** [comment]
I was expecting it to be available in config.

**Comment by WoodyLinwc** [comment]
When I go to my "About" page, the favicon just disappear. Do you guys know how to resolve it?
