### ISSUE TITLE
How to do SEO for jekyll-now based blog?

### ISSUE THREAD

**Issue by qqibrow** [barryclark/jekyll-now#61]
Hi, I made a blog based on jekyll-now and thank you for your great work! but the problem is I cannot find my blog in the first 5 page when searching in Google, which I think there might be some problem here. I am not very familiar with SEO, but how to do that for jekyll-now based blog?

**Comment by barryclark** [comment]
Hey @qqibrow there isn't much difference in doing SEO for a Jekyll based blog that any other site, so you can follow best practices that you find for any website.

Getting your blog within the first 5 pages of Google can take time, and there are a lot of different variables involved there. 

I'd recommend having a read of http://www.quicksprout.com/the-advanced-guide-to-seo/ to familiarize yourself more with SEO best practices.

**Comment by cauerego** [comment]
Damn, that's a really nice illustrated guide! Unlike mr brow, [I am *very* familiar with SEO (google for "stackoverlow seo, click on 3rd link"](http://meta.stackexchange.com/a/42105/143411) and I bet there are a few things I could still learn if I stop to read all that.

Now, it have been about 5 days I've built a github page with Jekyll, and Google still couldn't see its contents. I mean `site:coroachada.github.io` shows it's there, but when I try searching for `coroachada imagine` nothing pops up. _Maybe_ that's actually a problem with my landing page, though, which isn't fully in Jekyll (for random reasons)...

Just wanted to confirm with you, @barryclark : do you think this might be an issue with Jekyll? In other words, is there anything you know of that could be broken on the technical SEO aspect for cases as narrow as this?

**Comment by barryclark** [comment]
It's not an issue with Jekyll.

Have you listed the URL @cauerego? More info on how to do that here: https://support.google.com/webmasters/answer/6259634?hl=en

**Comment by cauerego** [comment]
It went away soon after I posted it, and I had listed the URL. Who knows? Maybe the crawlers got lost in the middle! ;P

**Comment by jiasir** [comment]
GitHub Pages can optimize your site for search engines and social media networks, using the Jekyll SEO tag plugin.
To enable the Jekyll SEO tag plugin, you must add the following line to your `site's _config.yml` file:
```
gems:
  - jekyll-seo-tag
```

To tell the plugin where to put your meta tag information, you must add the SEO tag right before `</head>` in your site template files. For example, in `_layouts/_default.html`:
```
<html>
  <head>
    {% include head.html %}
    {% seo %}
  </head>
</html>
```
