### ISSUE TITLE
Default to about page instead of blog page?

### ISSUE THREAD

**Issue by arendu** [barryclark/jekyll-now#643]
Hi, I am not sure if this is the right place for this question, but I am wondering if there is an easy way to change the default page to the `about` page and make a navigation link to the `blog posts` page.

More details about my question are here: http://stackoverflow.com/questions/39301831/jekyll-github-pages-navigation-issues

**Comment by emilypmendez** [comment]
Did you get this figured out @arendu ... What was the solution?

I understand going to `_layouts/default.html` and changing the order of navigation links in here. Although still struggling in discovering how to change the default page itself

**Comment by alexbovet** [comment]
@arendu @emilypmendez I am also interested to change the default page to the About page instead of the Blog posts. 
Did you figure out how to do it?
The link to the stackoverflow question is dead and I don't understand how @mariolameiras' commit fixed this issue...
