### ISSUE TITLE
preview draft posts on github ?

### ISSUE THREAD

**Issue by andysouth** [barryclark/jekyll-now#65]
Hi Barry, Thanks for your very helpful work which I've used to set up a [code centric blog](http://andysouth.github.io/).

I particularly liked not having to install jekyll etc. locally.

I've just realised that I can't think of a way to preview what a draft posts will look like without publishing it for everyone to see. My principal concern is that I don't want posts to be published by a particular feed aggregator until I've finished them. Any suggestions ?

Thanks,
Andy

**Comment by lostmsu** [comment]
@barryclark can you make this a default feature?
