### ISSUE TITLE
Adding new page

### ISSUE THREAD

**Issue by ashstr** [barryclark/jekyll-now#679]
I tried to add a new page by the following :

1- add new folder ' resume ' then add inside it a index.html file 
but nothing happened :(

2- add new file at the root of the project and rename it to resume.html 
but also nothing happened

I also tried to this 
`
---
layout: page
title: Resume
permalink: /Resume/
---
`

inside the 2 pages but still nothing too
...

**Comment by ashstr** [comment]
i think i found the solution ,
i edited the _layouts/default.html file and added my new page path like about and it worked

thanks guys :)

**Comment by miwilc** [comment]
can @ashstr or the maintainers close this issue

**Comment by cjerrington** [comment]
@barryclark, this issue is resolved. Thanks!
