### ISSUE TITLE
syntax Error in Github

### ISSUE THREAD

**Issue by 5y** [barryclark/jekyll-now#68]
Hi,
Github recognized style.scss Syntax error so when you forked , your github page doesn't active until some change in style.scss file.
what's  your comment about that?

Bests

**Comment by barryclark** [comment]
@5y I can't replicate this, do you still see that problem?

**Comment by barryclark** [comment]
Closing as I can't replicate this. Appears to be fixed now. We can re-open if it comes up again.

**Comment by 5y** [comment]
@barryclark Sorry i miss Github Notification,
I just test for several time on my account, you know Github spend 30 minute for active Blog but after that time it doesn't work until i rename style file. i have no any idea about that but i testing again and submit result here.

Cheers,
Reza

**Comment by barryclark** [comment]
Hey 5y, 

Could you detail the steps that you're going through to make this happen?

Also, note that it can take up to 10 minutes after forking for your site to go live.

**Comment by 5y** [comment]
Hey Barry , 
1- Forking jekyll-now and rename to myaccount.github.io
2- after 30 minutes for me I expected saw default jekyll-now page but i saw 404 Error.
3- it's repeated for several time until i changed Style.scss to style.css
and it's strange for!

**Comment by barryclark** [comment]
Hmm, thanks @5y. Does appear to be working now, though. I'll keep my eye on seeing if anyone else runs into this problem. I can't get it to happen :(

**Comment by 5y** [comment]
Thank you too @barryclark for answer to my not clear issue, jekyll-now is awesome and test it again if i find any issue,submit here precisely :)

Cheers,
Reza
