### ISSUE TITLE
Syntax highlighting and PHP

### ISSUE THREAD

**Issue by pixelbart** [barryclark/jekyll-now#688]
Hey guys!

I've a problem with Syntax highlighting an the language PHP. Their was'nt any Syntax highlighting for that, right?

Thanks guys!

**Comment by sanspace** [comment]
Are you using Rouge?

**Comment by pixelbart** [comment]
Good question. I'am using the default highlighter from jekyll now.

**Comment by sanspace** [comment]
It must be Rouge then. You can confirm it by the value of `syntax_highlighter` in your `_config.yml`. I could see some issues and a bugfix about PHP highlighting in Rouge Repo https://github.com/jneen/rouge/issues?utf8=%E2%9C%93&q=is%3Aissue%20php%20highlight . You will have to provide more details to know exactly if it's an issue with rouge or jekyll-now.

**Comment by pixelbart** [comment]
You can just looking here: https://github.com/pixelbart/pixelbart.github.io 

Is live on github. I post some markdown and php after the first riple backticks.

- https://pixelbart.github.io/PHP-Token/ ([2016-10-12-PHP-Token.md](https://github.com/pixelbart/pixelbart.github.io/blob/master/_posts/2016-10-12-PHP-Token.md))

Havent change anything. Just a simple fork from jekyll now. 

On the link you've posted ive seen thats the bug is resolved in rouge - because the first "issue" showing an php example (is a fout, but its worked!)

__Sorry for my bad english guy ;)__

**Comment by pixelbart** [comment]
Oh i think is a "highlighter" theme fout. I'm looking for an other theme, check it out and gave feedback. But now i'm going to bad. My wife want sleep. 

In germany is night 💃

**Comment by sanspace** [comment]
I could see the markdown file is rendered properly.

https://github.com/pixelbart/pixelbart.github.io/blob/master/_posts/2016-10-12-PHP-Token.md

But, not the post in your site.

https://pixelbart.github.io/PHP-Token/

I don't see (through viewsource) any highlighting related markup or styling in the page. May be it could be your theme as you say. But, I don't have much clue now. Please try switching the themes. Let's see if it helps.

**Comment by pixelbart** [comment]
Hey @sanspace :) I found the solusion: I've just add an <?php tag to the code block and its worked. Its not so "nice" but its ok. 

Thanks guy! ;)

Nice Github Theme: [github.css](https://github.com/richleland/pygments-css/edit/master/github.css)
