### ISSUE TITLE
Google Translate Bubble is broken

### ISSUE THREAD

**Issue by CYB3Rhuman** [barryclark/jekyll-now#72]
You can see it here: https://translate.google.com/translate?sl=en&tl=es&u=jekyllnow.com
![default](https://cloud.githubusercontent.com/assets/1071872/5628126/e3b5b694-95b3-11e4-9407-a51168471d8a.png)
Probably, it's the CSS Reset causing this transparent background of the bubble.
I should investigate more.

**Comment by barryclark** [comment]
Thanks for flagging this, @CYB3Rhuman. If you do get a chance to investigate a fix that'd be awesomeness. Let me know :)

**Comment by jaminscript** [comment]
I'm on it.

**Comment by jaminscript** [comment]
I believe I have resolved the issue. I will send my pull request shortly.

![google-translate-fix](https://cloud.githubusercontent.com/assets/2616473/5714007/c842209a-9b27-11e4-9e9d-20c8f6d5540a.png)

**Comment by CYB3Rhuman** [comment]
Thank you very much for this fix!
