### ISSUE TITLE
mathjax won’t run

### ISSUE THREAD

**Issue by bobsica** [barryclark/jekyll-now#749]
I have put in both my pages.html and post.html files:

<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

But have had no luck getting matjax to work. Any suggestions on what I’m doing wrong? It is not a syntax issue, even $$ y = x $$ doesn’t work. I neither see a rendered equation, nor do I see the literal text $$ y = x $$.

**Comment by TheMeaningfulEngineer** [comment]
Just got it working. Add `_includes/mathjax.html` containing:
```
<script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js"],
        jax: ["input/TeX", "output/HTML-CSS"],
        tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"] ],
          displayMath: [ ['$$','$$'], ["\[","\]"], ["\\[","\\]"] ],
          processEscapes: true
        },
        messageStyle: "none",
        "HTML-CSS": { availableFonts: ["TeX"] }
      });
    </script>
    <script type="text/javascript" 
            src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
            
    </script>
```

Modify your `_layout/default.html` to containt `{% include mathjax.html %}`.Example of how my looks:

```
$ tail default.html 
        <footer class="footer">
          {% include svg-icons.html %}
        </footer>
      </div>
    </div>

    {% include analytics.html %}
    {% include mathjax.html %}
  </body>
</html>
```

This get it running :)
Consider giving a few bucks to mathjax if it solved your issue, it's nice :)

**Comment by bobsica** [comment]
Thanks. I got it working by just putting the end mathjax script in my header include file, but I didn't put the syntax code before. Is that code necessary if you use kramdown, I assume it is to extend the syntax to be the same as MMD? I will try this. Also, good idea, I will support mathjax.

**Comment by TheMeaningfulEngineer** [comment]
> Is that code necessary if you use kramdown, I assume it is to extend the syntax to be the same as MMD?

Don't know sorry, I just had this reference which worked for me, didn't explore the concepts once it started working :)

**Comment by bobsica** [comment]
OK, I’ve looked into it (at least using jekyll with kramdown). Not all the “standard” multi-markdown/latex equation syntax works if you only include the script to connect to mathjax. The include code you gave me allows all permutations of $$, $, \\[ and \\( to work as expected. Thanks again.
