### ISSUE TITLE
Setting excerpt_separator Fails to Function

### ISSUE THREAD

**Issue by aaronharmon** [barryclark/jekyll-now#78]
First of all - thanks for this project, it's really powerful.

Question for you - in my config.yml I'm setting excerpt_separator: "/n/n"

However this doesn't appear to do anything. Is there a way to easily update the excerpt_separator configuration variable?

**Comment by barryclark** [comment]
Hi @aaronharmon,

Thanks!

I've actually never used the excerpt_separator configuration flag myself, but I Google'd around a bit for some related threads, hopefully these help with a fix:

- https://github.com/jekyll/jekyll/issues/1839 (relevant as Jekyll Now uses redcarpet)
- http://stackoverflow.com/questions/16422933/how-do-i-use-markdownify-in-jekyll-to-show-an-excerpt-on-the-index (a good excerpt_separator example)

Couldn't see any of your code to take a peek at, but if I can help any more just give me a shout.

**Comment by aaronharmon** [comment]
Thank you, that worked perfectly!

**Comment by barryclark** [comment]
Yay! Glad that you got it working :)

**Comment by StefanKrauth** [comment]
I have exactly thesame issue and worked around it by changing the page and post layout to embed

{{ content | replace: '', '' }}

This cuts out the excerpt separator from the page and everything works as expected.
