### ISSUE TITLE
Swift code highlight problem

### ISSUE THREAD

**Issue by lukzmu** [barryclark/jekyll-now#785]
When I try to paste my code using the  "```Swift" tag everything is okay on Github page editor, but once it lands on Jekyll blog post it looses all flavour - no colors, no border, no anything - just plain text.

On the other hand if I add just "```" then the code appears in a border (no colors tho)

**Comment by jeremiahflaga** [comment]
Use the small letter "s" in Swift (like the small caps JavaScript below):

``` javascript
function test() {
    console.log("test");
}
```

The list of the aliases for the languages supported are here: https://github.com/jneen/rouge/wiki/List-of-supported-languages-and-lexers
