### ISSUE TITLE
Render math equations? 

### ISSUE THREAD

**Issue by rohan-varma** [barryclark/jekyll-now#802]
This has been a lifesaver for setting up my blog. I want to include some math equations in some of my posts, and haven't been able to figure out how to include them, other than using a latex-to-image service and then uploading the images. Is there a better way to do this?

**Comment by mmistakes** [comment]
@rohan-varma Have you tried [MathJax](https://www.mathjax.org/#docs)? You just have add a script to your post/page layout and if you're using Kramdown (Jekyll's default Markdown processor) you should be good to go.

**Comment by rohan-varma** [comment]
Thanks! Looks like this did the job for me.

**Comment by dshahrokhian** [comment]
@rohan-varma @mmistakes would you kindly tell me to which file did you add the MathJax script?

`<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/0.1/MathJax.js?config=TeX-MML-AM_CHTML'></script>
`

**Comment by dshahrokhian** [comment]
Nevermind, the problem was integration url shown in the mainpage of MathJax (404 not found). I chose a different script from [this](https://github.com/act65/act65.github.io/blob/master/_includes/mathjax.html) forked repo, and added it to `_layouts/post.html`.

**Comment by rohan-varma** [comment]
Awesome, glad it worked for you!
