### ISSUE TITLE
Posts will not render unless title date/month are two digits

### ISSUE THREAD

**Issue by chipbuster** [barryclark/jekyll-now#804]
I'm not sure if this is something that was intentional (I only started using Jekyll yesterday), but I was unable to get any markdown files in _posts to render unless I the date and month fields in the name were two digits each, i.e. `2014-3-3-Hello-World.md` had to be titled `2014-03-03-Hello-World.md` before `site.posts` would pick up on it.

This happened on both my laptop (macOS 10.12.3) and my desktop (Arch Linux). Both are running Jekyll 3.4.0.

**Comment by cjerrington** [comment]
That is the way Jekyll requires the date formats to be. https://jekyllrb.com/docs/posts/

**Comment by jkpark** [comment]
Yes, I started using Jekyll just before and I changed my markdown file name as you said. and I works. Thanks

**Comment by cjerrington** [comment]
Awesome, could you close the issue for us?
