### ISSUE TITLE
Layout with Bootstrap template

### ISSUE THREAD

**Issue by AmauryVanEspen** [barryclark/jekyll-now#806]
Good evening,

i would like to know, how could it be possible to work with a bootstrap template, 
for exemple, one of these ? https://startbootstrap.com/template-categories/all/

Thank you for your kind collaboration

Amaury

**Comment by AmauryVanEspen** [comment]
For exemple, is it compatible with http://jekyllbootstrap.com/ ?

**Comment by cjerrington** [comment]
Not exactly, but if you wanted to use elements from bootstrap you can always include the CSS and JavaScript elements needed. But a full column grid, no.

**Comment by AmauryVanEspen** [comment]
Thank you,
i'm still looking for a tutorial in order to learn how to do it,
(more than manually copy/paste, there is maybe a way that i didn't know or didn't understand to use twitter bootstrap template & framework).
Thank you for your kind answer =)

One more question, could you tell me (or let me know where i can get the right doc) why is it no possible to work with column in jerkyll ?

Thanks,

Amaury

**Comment by cjerrington** [comment]
For the themes found on [Startbootstrap](https://startbootstrap.com/template-categories/all/) some individuals have modified the html template to work with jekyll by creating an includes, posts, etc pages and folders. [Jekyll](https://jekyllrb.com) in itself is only a platform and programming language like PHP or ASP and the like. 

Jekyll is based off Ruby and uses what is called Front Matter and Liquid tags. Twitter Bootstrap is the html framework to render the html pages. Jekyll in this case is the compiler and backend for the hosting off [Github pages](https://pages.github.com). [Jekyll Now](http://www.jekyllnow.com) was created by [Barry Clark](http://www.barryclark.co/) as a one column blog style website. 

I think this issue can be closed, but feel free to reach out to me and I can explain more on a different platform. 

Resources:
- [Jekyll](https://jekyllrb.com)
- [Jekyll Docs](https://jekyllrb.com/docs/home/)
- [Github pages](https://pages.github.com)
- [Barry Clark](http://www.barryclark.co/)
- [Jekyll Now](http://www.jekyllnow.com)
