### ISSUE TITLE
Layout and code font

### ISSUE THREAD

**Issue by mohanr** [barryclark/jekyll-now#856]
I have these two questions.
1. How do I increase the page width globally ?
2. Is there anything in this theme that will help me reduce the Pygments or Rouge code font size ?

**Comment by Pugzy** [comment]
@mohanr To resolve the first issue you could modify the `container`s `max-width` within the CSS (style.css) file or include your own stylesheet and override the default there.

**Comment by mohanr** [comment]
Yes. It works.
 This changed the size of the code font in 

__highlights.scss_

                   pre,
                   code {
                       font-size: 15px;
   
                  }
