### ISSUE TITLE
PageLayout

### ISSUE THREAD

**Issue by akshay-babbar** [barryclark/jekyll-now#860]
Hi Barry,
First of all Thanks for creating this repository which has given me a great opportunity to publish my Blog !!
My question is when I try to edit the about markdown,I think there is a limit as to how many words can come on a single line .
Now by default very few words  can come in  a single line and I want more.

Can you please tell me the way forward?

Regards
Akshay

**Comment by janfitz** [comment]
Hi, you can resolve this easily by editing `style.scss` file in root of your blog (it changed your page layout globally) or make some special styles and layout only for `aboud.md` file. 

- Make new file in `_layout` folder named for instance `about.html` and copy the content of some other .html file in

- Edit `style.scss` file by adding new class named for instance `about`

- Rename class in your new `about.md` file to `about`

- In `ABOUT.md` file change first line to `layout: about`

I think that this should help.
