### ISSUE TITLE
Trying to fix the About page to utilize my content instead of the default

### ISSUE THREAD

**Issue by andrewsunglaekim** [barryclark/jekyll-now#88]
For whatever reason the about page content doesn't change. I took the _site folder off of my git ignore, but its still not updating the Git hub page.

**Comment by barryclark** [comment]
Did you get this working @andrewsunglaekim?

Editing the about page markdown file is all you need to do to change the content. _site on git ignore doesn't have anything to do with it. Sounds like there was some other reason (maybe from a different commit) that was causing your build to fail.
