### ISSUE TITLE
404 is not displayed

### ISSUE THREAD

**Issue by JonLan2002** [barryclark/jekyll-now#896]
When I enter something that does not exist like "https://jonlan2002.github.io/abc123" I see the 404 page of github instead of 404.md.

**Comment by databhishek** [comment]
Just add
`permalink: /404.html `
to the front matter of 404.md. It should work then.

**Comment by sreetamdas** [comment]
@JonLan2002 has your issue been resolved?

**Comment by JonLan2002** [comment]
It works!
Thanks!
