### ISSUE TITLE
Page build error.

### ISSUE THREAD

**Issue by gafanhotz** [barryclark/jekyll-now#91]
Hello there! I just forked and copied it to my io repo and it returned a build error without specific reason, anyone got it too?

**Comment by barryclark** [comment]
Looks like you're up and running now, @gafanhotz?

**Comment by gafanhotz** [comment]
Curiously yes, I removed the line ```![_config.yml]({{ site.baseurl }}/images/config.png)``` from the Hello World post and got it running.

**Comment by barryclark** [comment]
Got it. Not too sure why that was. Maybe the site just needed to Jekyll build for the first time. :)
