### ISSUE TITLE
Emoji is not working

### ISSUE THREAD

**Issue by prihandoko** [barryclark/jekyll-now#93]
Emoji is not working. I don't know what's wrong. I forked this repository and only change CNAME and _config.yml

thanks. 

my site: rudi.prihandoko.id
source: https://github.com/prihandoko/prihandoko.github.io

**Comment by barryclark** [comment]
Hi @prihandoko, 

I removed emoji support around a week ago because the little emoji images it includes get displayed badly in screen readers like Pocket, making sites look really unprofessional.

**Comment by Koxzi95** [comment]
For the emoji was only one version useable? Such as Twitter etc?

**Comment by prihandoko** [comment]
@barryclark thanks for the explanation. Maybe you should change some in features list, e.g. as in the homepage of jekyll now (http://www.jekyllnow.com/) so people do not misunderstand. 
btw, thanks for the repo. :)

**Comment by barryclark** [comment]
@prihandoko good call. Thanks for alerting me of that, I'll change it soon.

**Comment by barryclark** [comment]
Closing this out as I've updated www.jekyllnow.com to no longer include any information about emoji.
