### ISSUE TITLE
"Or you can use your GitHub profile pic"

### ISSUE THREAD

**Issue by DaveVdE** [barryclark/jekyll-now#97]
I saw this mentioned in the configuration file. Could you clarify how one uses his GitHub profile pic?

**Comment by Koxzi95** [comment]
In the config: 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/6239399?v=2&s=460

**Comment by DaveVdE** [comment]
OK, so just use the URL of the image in the Profile page. 

Thanks!

**Comment by barryclark** [comment]
Thanks for answering, @Koxzi95 :smiley:

**Comment by HKhademian** [comment]
Use this [stackoverflow answer](https://stackoverflow.com/a/36380674/1803735)
attention max size is 460px

> https://github.com/twbs.png
> https://github.com/npm.png?size=200
> https://github.com/github.png?size=40

**Comment by brucechanglongxu** [comment]
Thank you!
